# Generated by Django 2.2a1 on 2019-03-20 09:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import user_details.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_air', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1), user_details.validation.validate_zero])),
                ('mains_air', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1), user_details.validation.validate_zero])),
                ('state', models.CharField(choices=[('andhra pradesh', 'Andhra Pradesh'), ('arrunachal pradesh', 'Arrunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chattisgarh', 'Chattisgarh'), ('goa', 'Goa'), ('gujrat', 'Gujrat'), ('haryana', 'Haryana'), ('himachal pradesh', 'Himachal Pradesh'), ('jammu & kashmir', 'Jammu & Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttarakhand', 'Uttharakhand'), ('uttar pradesh', 'Uttar Pradesh'), ('west bengal', 'West Bengal')], max_length=100)),
                ('category', models.CharField(choices=[('general', 'General'), ('general-pwd', 'General-PwD'), ('obc-ncl', 'OBC-NCL'), ('obc-ncl-pwd', 'OBC-NCL-PWD'), ('sc', 'SC'), ('st', 'ST')], max_length=100)),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True)),
                ('Logged_in_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FillPrefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_selected', multiselectfield.db.fields.MultiSelectField(choices=[('Indian Institute of Technology Bombay, Aerospace Engineering', 'Indian Institute of Technology Bombay, Aerospace Engineering'), ('Indian Institute of Technology Bombay, Chemical Engineering', 'Indian Institute of Technology Bombay, Chemical Engineering'), ('Indian Institute of Technology Bombay, Civil Engineering', 'Indian Institute of Technology Bombay, Civil Engineering'), ('Indian Institute of Technology Bombay, Computer Science and Engineering', 'Indian Institute of Technology Bombay, Computer Science and Engineering'), ('Indian Institute of Technology Bombay, Electrical Engineering', 'Indian Institute of Technology Bombay, Electrical Engineering'), ('Indian Institute of Technology Bombay, Electronics and Communication', 'Indian Institute of Technology Bombay, Electronics and Communication'), ('Indian Institute of Technology Bombay, Mechanical Engineering', 'Indian Institute of Technology Bombay, Mechanical Engineering'), ('Indian Institute of Technology Delhi, Aerospace Engineering', 'Indian Institute of Technology Delhi, Aerospace Engineering'), ('Indian Institute of Technology Delhi, Chemical Engineering', 'Indian Institute of Technology Delhi, Chemical Engineering'), ('Indian Institute of Technology Delhi, Civil Engineering', 'Indian Institute of Technology Delhi, Civil Engineering'), ('Indian Institute of Technology Delhi, Computer Science and Engineering', 'Indian Institute of Technology Delhi, Computer Science and Engineering'), ('Indian Institute of Technology Delhi, Electrical Engineering', 'Indian Institute of Technology Delhi, Electrical Engineering'), ('Indian Institute of Technology Delhi, Electronics and Communication', 'Indian Institute of Technology Delhi, Electronics and Communication'), ('Indian Institute of Technology Delhi, Mechanical Engineering', 'Indian Institute of Technology Delhi, Mechanical Engineering'), ('National Institute of Technology Surathkal, Chemical Engineering', 'National Institute of Technology Surathkal, Chemical Engineering'), ('National Institute of Technology Surathkal, Civil Engineering', 'National Institute of Technology Surathkal, Civil Engineering'), ('National Institute of Technology Surathkal, Computer Science and Engineering', 'National Institute of Technology Surathkal, Computer Science and Engineering'), ('National Institute of Technology Surathkal, Electrical Engineering', 'National Institute of Technology Surathkal, Electrical Engineering'), ('National Institute of Technology Surathkal, Electronics and Communication', 'National Institute of Technology Surathkal, Electronics and Communication'), ('National Institute of Technology Surathkal, Information Technology', 'National Institute of Technology Surathkal, Information Technology'), ('National Institute of Technology Surathkal, Mechanical Engineering', 'National Institute of Technology Surathkal, Mechanical Engineering'), ('National Institute of Technology Trichy, Chemical Engineering', 'National Institute of Technology Trichy, Chemical Engineering'), ('National Institute of Technology Trichy, Civil Engineering', 'National Institute of Technology Trichy, Civil Engineering'), ('National Institute of Technology Trichy, Computer Science and Engineering', 'National Institute of Technology Trichy, Computer Science and Engineering'), ('National Institute of Technology Trichy, Electrical Engineering', 'National Institute of Technology Trichy, Electrical Engineering'), ('National Institute of Technology Trichy, Electronics and Communication', 'National Institute of Technology Trichy, Electronics and Communication')], max_length=1687)),
                ('Logged_in_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
