# Generated by Django 2.2a1 on 2019-03-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_giveresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillprofile',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST')], max_length=100),
        ),
    ]
