# Generated by Django 2.2a1 on 2019-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_auto_20190324_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillprofile',
            name='adv_air',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fillprofile',
            name='mains_air',
            field=models.PositiveIntegerField(),
        ),
    ]
